### ISSUE TITLE
Regarding openshift

### ISSUE THREAD

**Issue by shravn9** [shekhargulati/todo-flask-openshift-quickstart#1]
I have created an openshift account as per the prerequisites but when i run the command
$ rhc app create todo python-2.7 postgresql-9.2
and enter my login credentials it says 

"The OpenShift Online (Next Gen) Developer Preview is here! We will not be
accepting new users onto the OpenShift Online (v2) platform. "

Is there any other way that i could run the todo application ?

**Comment by shekhargulati** [comment]
@shravn9 Not that I am aware of. You have to signup for next version of OpenShift Online
